version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: requirements.txt
    - requirements: dev-requirements.txt
    - toml
